services:
  db:
    image: postgres:16-alpine
    container_name: cinema_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_cinema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: